name: Daily scrape

on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches: [ main ]

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run scrape.py
        run: python scrape.py
      - name: Commit changes
        uses: EndBug/add-and-commit@v7
        with:
          author_name: "Josh"
          author_email: "josh@joshelliott.me"
          message: "Updated player data"
          add: "data/*"
      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
